services:
  - type: web
    name: ai-dashboard-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn api.predict:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: OPENWEATHERMAP_API_KEY
        sync: false

  - type: web
    name: ai-dashboard-rppg
    runtime: python
    rootDir: rppg_backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars: []
